CIRCUITPY_WIFI_PASSWORD = "radioamatore@2"
CIRCUITPY_WIFI_SSID = "FRITZ!Box 7530 NM"

TEL_SSID = "Rete"
TEL_PASSWD = "mebv8087"

MQTT_IP = "155.185.4.4"
MQTT_PORT = "7883"

MQTT_USERNAME = "324749@studenti.unimore.it"
MQTT_PASSWORD = "xdkjltekfseyslaq"
MQTT_BASIC_TOPIC = "/iot/user/324749@studenti.unimore.it/device"
MQTT_DEVICE_INFO_TOPIC = "/info"
MQTT_DEVICE_SETTINGS_TOPIC = "/settings"
MQTT_BASE_TELEMETRY = "/telemetry"
MQTT_TEL_SH = "/sh"
MQTT_TEL_AH = "/ah"
MQTT_TEL_TEMP = "/temp"
MQTT_TEL_WATER = "/water"